import streamlit as st
def show_help():
        
    st.title("Need Help?")
    st.write("#")
    st.header(":white[FAQ]")
    st.write("###")
    st.subheader(':white[What is Assets.AI?]')
    st.write('This is a website that helps you to accumuliate and handle all your assets with the help of ml techniques. We are a SaaS based brand based on Surat, Gujarat, India. Our motive is to provide Finance with Data Science related softwares for better experience and executation.')
    st.write("#")
    st.subheader('What are our Products?')
    st.write('Currently we are providing four products. Namely Stocks, Gold, Real Estate and Crypto. Each of the products have their own functionality that helps decision drive easy.')
    st.write("#")
    st.subheader('What is Stocks tab?')
    st.write('The Stock tab is used for gathering information about the stocks. This tab contain Three parts: Main, Prediction and Sentiment. ')
    st.write("#")
    st.subheader('What is Gold tab?')
    st.write('This tab is used for forecasting the gold prices with the help of previous data.')
    st.write("#")
    st.subheader('What is Real Estate tab?')
    st.write('This tab is used for Checking and analysing the property prices per sqft in different cities and in different year. This tab further have two parts namely: buy and rent.')
    st.write("#")
    st.subheader('What is Crypto tab?')
    st.write('This tab is used for tracking the crypto prices in realtime. Nine trackers are provided in side bar. So, that the comarision of all data is not conjusting but easy.')
    st.write("#")
    st.subheader('What is Dash tab?')
    st.write('This tab is used for tracking all your earnings and expenses in a particular month. This helps to take the foot prints of early spendings and help for better analysing.')
    st.write("#")
    st.subheader('What is Community tab?')
    st.write('This is a community tab, here you can post your queries, ideas, solutions and can share your thoughts related to the system with other assest.AI members.')
    st.write("#")

    st.write("#")
    st.header("Still have a query? Contact US")
    st.write("contact details")